/*

 * 1.2 version.
 */

import java.awt.image.*;
import java.text.DecimalFormat;
import java.util.Calendar;
import java.util.Date;

/* 
 * This is like the FontDemo applet in volume 1, except that it 
 * uses the Java 2D APIs to define and render the graphics and text.
 *
 * read data file data5day generated by Script c.data5day
 */

public class GetByRandom 
{
//start of program
	public static void main(String[] args)
	{
		long timeNow=(new Date()).getTime();
		Calendar aTime=Calendar.getInstance();
		int iHr=aTime.get(Calendar.HOUR_OF_DAY);
		int iMin=aTime.get(Calendar.MINUTE);
		int eodHr=06, eodMin=55; 
		long timeEnd=timeNow+(((eodHr-iHr)*3600+(eodMin-iMin)*60)*1000);
		int[] testR=new int[40];
		while (timeNow < timeEnd) {
			double x=(0.025+Math.random())*40;
			int k=(int)Math.floor(x);
			k %= 39;
			if (k < 1) k=1;
			testR[k]++;	
			try {
				
				Thread.sleep(200);
			}catch (InterruptedException e){}
			timeNow += 200;
		}
		
		for (int i=1; i<40; i++){
			System.out.print(""+i+"["+testR[i]+"],");
			if (i % 8 == 0) System.out.println("");
		}
		System.out.println("");
	}

}
