/*
 * 1.2 version.
 */

import java.io.*;
import java.util.Arrays;
/*
import java.util.*;
*/
import java.util.Date;
import java.util.Calendar;
import java.util.HashMap;
//import java.util.regex.*;
import java.awt.*;
import java.text.DecimalFormat;
import java.awt.geom.*;

import javax.swing.*;

import java.awt.image.*;

import javax.imageio.*;

import java.io.File;
import java.util.Vector;
import java.io.IOException;
import java.lang.Thread;

/* 
 * This is like the FontDemo applet in volume 1, except that it 
 * uses the Java 2D APIs to define and render the graphics and text.
 *
 * read data file data5day generated by Script c.data5day
 */

public class PermuteDataMath 
{
/**
	
	 */
	
public static void main(String[] args)
{
	BufferedWriter aWriter;
	try {
		aWriter=new BufferedWriter(new OutputStreamWriter(new FileOutputStream("permute539.txt")));
		int iC=0;
	for (int n1=1; n1<36; n1++){
		for (int n2=n1+1; n2<37; n2++){
			for (int n3=n2+1; n3<38; n3++){
				for (int n4=n3+1; n4<39; n4++){
					for (int n5=n4+1; n5<40; n5++){
						aWriter.write("("+(++iC)+")-"+n1+"-"+n2+"-"+n3+"-"+n4+"-"+n5);
						aWriter.newLine();
					}
				}
			}
		}
	}
	aWriter.close();
	System.out.println("Total "+iC);
	} catch (FileNotFoundException e){
		System.out.println("No file");
} catch (IOException e){
	System.out.println("Bad I/O");
}
		
		
}
}
