/*

 * 1.2 version.
 */

import java.awt.image.*;

/* 
 * This is like the FontDemo applet in volume 1, except that it 
 * uses the Java 2D APIs to define and render the graphics and text.
 *
 * read data file data5day generated by Script c.data5day
 */

public class ImgFactory 
{
//start of program
	private static final int max1=5, rectX=600, rectY=500;
	private static int inhouse=0;
   private static BufferedImage[] mineImg=new BufferedImage[max1];
	private static int max=5;
	
	synchronized static BufferedImage getImg()
	{
	BufferedImage returnImg=null;
		if (inhouse < max)
		{
			try {
			returnImg=new BufferedImage(rectX, rectY, BufferedImage.TYPE_INT_ARGB);
			} catch (OutOfMemoryError e) {max=inhouse;}
			if (returnImg != null){mineImg[inhouse++]=returnImg;}
		}
		if (returnImg==null)
		returnImg=mineImg[inhouse++ % max];
		
		return returnImg;		 
	}
	

//end of program

public static void main(String[] args)
{
BufferedImage getImg;
for (int i=0; i<100; i++)
	{
	getImg=ImgFactory.getImg();
		System.out.println("<"+i+">"+getImg.toString());
	}
	System.out.println("Done");


}
}
